### ISSUE TITLE
Can't read message.json

### ISSUE THREAD

**Issue by abindadna** [t0xic-m/instagram_json_viewer#11]
Hi, I can't read the message.json file from the latest update of Instagram. Is there any solution?

**Comment by t0xic-m** [comment]
Hello,

so just to clarify - 
[1] your instagram zip-file contains the messages.json and it can't be read 
/ or 
[2] it doesn't contain the file and the generated messages.json can't be read?

For [1] try the older version of the script which can be found here:
https://github.com/t0xic-m/instagram_json_viewer/tree/v2020.12.07
For [2] I am still adapting and waiting to get my hands on the newer data, which should hopefully happen in the next week or so.

**Comment by abindadna** [comment]
Thank you for replying. I backed up on December 27, 2002. I got a new Instagram structure. There is no message.json in that folder. But when I run it with your python code, the message.json file appears. I think it's because of the structure update from Instagram. I hope to finish this issue soon. Thanks!

**Comment by sariette** [comment]
Hello,

The messages.json is generated.

The errors I get are:`

- KeyError('Other User')
- AttributeError("module 'datetrime' has no attribute 'fromtimestamp'")
- KeyError('restricted_users')
- KeyError('direct')
- (KeyError('story_comment')

These issues have affected all conversations.

Thank you for your great support!

**Comment by t0xic-m** [comment]
Hey,

I am aware of the problem, unfortunately I am currently having issues with instagram itself and don't have the data to reproduce this yet - their data download tool seems to be broken for me. 

Once I have the data I will hopefully be able to resolve this soon.

Sorry for the inconvenience!

**Comment by sariette** [comment]
You did great on the messages part. It is now integrated in the results. But we cannot see the name of the sender! Thank you for your great work!

**Comment by t0xic-m** [comment]
@sariette thanks for the feedback.

I got my own data today so I hopefully fixed everything so far, could you try with the script from this branch:
https://github.com/t0xic-m/instagram_json_viewer/tree/v2020.12.23

Or the script directly from here:
https://github.com/t0xic-m/instagram_json_viewer/raw/v2020.12.23/instaview.py

It should now work completely!
