### ISSUE TITLE
KeyError: 'Username\x9d¤'

### ISSUE THREAD

**Issue by Benji005** [t0xic-m/instagram_json_viewer#16]
Traceback (most recent call last):
  File "F:\instaview.py", line 1039, in read_messages
    html_chat_string = html_chat_string + "\t<img src=\"" + str(avatars[message["sender_name"]]) + "\" alt=\"" + str(message["sender_name"]).upper() + "\" class=\"right\" style=\"width:100%;\">\n"

KeyError: 'Username\x9d¤'

The above error keeps throwing up for all the id's in my chat and hence the message.json is not getting converted.

**Comment by t0xic-m** [comment]
Is this 'Username\x9d¤' your username?
I don't exactly know what the problem is but I would suspect that is has something to do with the encoding and that python doesn't like the special character in there. Hard to say without the data unfortunately.

**Comment by Benji005** [comment]
Yes the username is My username. Will you able if i provide you with a part of my one the message json files?

**Comment by t0xic-m** [comment]
Could you try with this version of the script if that fixes the error for you?

https://raw.githubusercontent.com/t0xic-m/instagram_json_viewer/bugfix_un-encoding/instaview.py

**Comment by Benji005** [comment]
Yeah.. It worked. Thanks a lot!
