### ISSUE TITLE
Changes with the instagram backup strutcture again ?

### ISSUE THREAD

**Issue by eelouise** [t0xic-m/instagram_json_viewer#22]
I would love to use this python to view old instagram dms so I downloaded my instagram backup but the directory is very different so the script doesn't read any of the files.
https://i.imgur.com/GH22DyS.jpg
^^ this is what i got from instagrams backup and a lot of the json file names have changed

**Comment by t0xic-m** [comment]
@eelouise Thanks for informing me! I will look into it as soon as possible!

**Comment by t0xic-m** [comment]
@eelouise so I just saw that instagram actually has the option now to download everything in HTML, which is basically what my tool does - except instagram does it way better than me of course haha
So you should be able to just download your data in HTML format and view your chats that way! ;)
If you already downloaded it in JSON format, you will have to wait for 4 days to make the other option available again afaik

**Comment by eelouise** [comment]
oh really well ill have to try that ina  few days.. thankyou for checking it out :)
