### ISSUE TITLE
Restructure of messages.json

### ISSUE THREAD

**Issue by t0xic-m** [t0xic-m/instagram_json_viewer#5]
Seems like instagram changed the file structuring (again).
Have to still confirm with my own data but looks like it with newer accounts.
Possibly have to merge json files first or recursively parse them in subfolders.

**Comment by albyaty** [comment]
Thank you for noticing this! 
I just added a comment on your youtube video, I thought you were not aware of this. 
 would really appreciate an update :) thank you so much

**Comment by t0xic-m** [comment]
Works on my end now - if there still issues, feedback would be appreciated!

**Comment by t0xic-m** [comment]
New changes should fix this issue.
Unsure about how many new json keys exist -> could be improved with more input.

**Comment by t0xic-m** [comment]
Issue is further tracked in #10
